<?php

function field_to_paragraph_update_1003(&$sandbox)
{
  //We are using the sandbox variable to update in batches of 25
  if (!isset($sandbox['progress'])) {
    $query = new EntityFieldQuery();
    $count = $query->entityCondition('entity_type', 'node', '=')
      ->entityCondition('bundle', 'article')
      ->count()
      ->execute();

    $sandbox['progress'] = 0;
    $sandbox['max'] = $count;

  }

  $query = new EntityFieldQuery();
  $result = $query->entityCondition('entity_type', 'node', '=')
    ->entityCondition('bundle', 'page')
    ->range($sandbox['progress'], 100)
    ->execute();

  $nodes = entity_load('node', array_keys($result['node']));

  foreach ($nodes as $node) {
      try {
        $entity = entity_create(
          'paragraphs_item',
          ['field_name' => 'field_paragraphs', 'bundle' => 'body']
        );
        $entity->setHostEntity('node', $node);
        $entity->field_body_paragraph = [
          LANGUAGE_NONE => [
            [
              'value' => $node->body['und'][0]['value'],
              'summary' => $node->body['und'][0]['summary'],
              'format' => $node->body['und'][0]['format']
            ],
          ],
        ];
        /*$entity->pfp_columns = [
          LANGUAGE_NONE => [
            [
              'value' => 'pfp-colauto'
            ],
          ],
        ];*/
        $entity->save();
      } catch (Exception $e) {
        watchdog(
          'field_to_paragraph',
          'Problem with node @node_id',
          ['@node_id' => $node->vid],
          WATCHDOG_ERROR
        );
      }

    $sandbox['progress']++;
  }

  watchdog('field_to_paragraph', 'Processed :progress / :count page', array(
    ':progress' => $sandbox['progress'],
    ':count' => $sandbox['max'],
  ));

  $sandbox['#finished'] = empty($sandbox['max']) || empty($node) ? 1 : ($sandbox['progress'] / $sandbox['max']);

}
